import express
import passport
export router

router = express.Router()

router.route('/login').get((req, res) ->
    res.render('login')
).post(
    passport.authenticate('local', { successRedirect: '/',
                                     failureRedirect: '/auth/login',
                                     failureFlash: true })
)

router.get('/logout', (req, res) ->
  req.logout()
  res.redirect('/')
)
