export {
  "ref": "refs/heads/master",
  "after": "1edd67c078c1767031452ddc2dfd3c5f46d96081",
  "before": "3ed49707cc13efedb71c46445da94159688a4621",
  "created": false,
  "deleted": false,
  "forced": false,
  "compare": "https://github.com/webkom/coffee/compare/3ed49707cc13...1edd67c078c1",
  "commits": [
    {
      "id": "1edd67c078c1767031452ddc2dfd3c5f46d96081",
      "distinct": true,
      "message": "add make production",
      "timestamp": "2014-09-12T12:05:12+02:00",
      "url": "https://github.com/webkom/coffee/commit/1edd67c078c1767031452ddc2dfd3c5f46d96081",
      "author": {
        "name": "Rolf Erik Lekang",
        "email": "me@rolflekang.com",
        "username": "relekang"
      },
      "committer": {
        "name": "Rolf Erik Lekang",
        "email": "me@rolflekang.com",
        "username": "relekang"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "Makefile"
      ]
    }
  ],
  "head_commit": {
    "id": "1edd67c078c1767031452ddc2dfd3c5f46d96081",
    "distinct": true,
    "message": "add make production",
    "timestamp": "2014-09-12T12:05:12+02:00",
    "url": "https://github.com/webkom/coffee/commit/1edd67c078c1767031452ddc2dfd3c5f46d96081",
    "author": {
      "name": "Rolf Erik Lekang",
      "email": "me@rolflekang.com",
      "username": "relekang"
    },
    "committer": {
      "name": "Rolf Erik Lekang",
      "email": "me@rolflekang.com",
      "username": "relekang"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "Makefile"
    ]
  },
  "repository": {
    "id": 14572118,
    "name": "coffee",
    "full_name": "webkom/coffee",
    "owner": {
      "name": "webkom",
      "email": null
    },
    "private": false,
    "html_url": "https://github.com/webkom/coffee",
    "description": "An API to the Moccamaster at the Abakus office",
    "fork": false,
    "url": "https://github.com/webkom/coffee",
    "forks_url": "https://api.github.com/repos/webkom/coffee/forks",
    "keys_url": "https://api.github.com/repos/webkom/coffee/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/webkom/coffee/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/webkom/coffee/teams",
    "hooks_url": "https://api.github.com/repos/webkom/coffee/hooks",
    "issue_events_url": "https://api.github.com/repos/webkom/coffee/issues/events{/number}",
    "events_url": "https://api.github.com/repos/webkom/coffee/events",
    "assignees_url": "https://api.github.com/repos/webkom/coffee/assignees{/user}",
    "branches_url": "https://api.github.com/repos/webkom/coffee/branches{/branch}",
    "tags_url": "https://api.github.com/repos/webkom/coffee/tags",
    "blobs_url": "https://api.github.com/repos/webkom/coffee/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/webkom/coffee/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/webkom/coffee/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/webkom/coffee/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/webkom/coffee/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/webkom/coffee/languages",
    "stargazers_url": "https://api.github.com/repos/webkom/coffee/stargazers",
    "contributors_url": "https://api.github.com/repos/webkom/coffee/contributors",
    "subscribers_url": "https://api.github.com/repos/webkom/coffee/subscribers",
    "subscription_url": "https://api.github.com/repos/webkom/coffee/subscription",
    "commits_url": "https://api.github.com/repos/webkom/coffee/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/webkom/coffee/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/webkom/coffee/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/webkom/coffee/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/webkom/coffee/contents/{+path}",
    "compare_url": "https://api.github.com/repos/webkom/coffee/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/webkom/coffee/merges",
    "archive_url": "https://api.github.com/repos/webkom/coffee/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/webkom/coffee/downloads",
    "issues_url": "https://api.github.com/repos/webkom/coffee/issues{/number}",
    "pulls_url": "https://api.github.com/repos/webkom/coffee/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/webkom/coffee/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/webkom/coffee/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/webkom/coffee/labels{/name}",
    "releases_url": "https://api.github.com/repos/webkom/coffee/releases{/id}",
    "created_at": 1384989509,
    "updated_at": "2014-09-11T16:59:39Z",
    "pushed_at": 1410516328,
    "git_url": "git://github.com/webkom/coffee.git",
    "ssh_url": "git@github.com:webkom/coffee.git",
    "clone_url": "https://github.com/webkom/coffee.git",
    "svn_url": "https://github.com/webkom/coffee",
    "homepage": "kaffe.abakus.no",
    "size": 855,
    "stargazers_count": 11,
    "watchers_count": 11,
    "language": "Python",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 4,
    "forks": 0,
    "open_issues": 4,
    "watchers": 11,
    "default_branch": "master",
    "stargazers": 11,
    "master_branch": "master",
    "organization": "webkom"
  },
  "pusher": {
    "name": "relekang",
    "email": "me@rolflekang.com"
  }
}
